language: generic
sudo: enabled
os: linux
install:
- ". ./scripts/ensure_latex.sh"
- "./scripts/ensure_book_dependencies.sh"
script:
- cd tex
- pdflatex paper.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  api-key:
    secure: bzdS60gHwVDME0FT7VHj4Ixl/dBbp016PqMc3T64oDesQA7BFxqpDuoQA1O2Vb0XpYA/x+/y3sAtlU/qygYeZKZjR52DwivGkfix3bzyLKrGe7tRElXqr54WDh9L7tR/u8/ud2kPRI27jbbnHfAIGWhPBqOtqHX6dr5lpIfDE9ioLYR25Mz536hTiRVUEbRb1PXEmMpx6vkT8Zop+3OUrOJgvw9xBFrRuJufJN6zDikBpgIDOig0RQ4qKWpjxDJQU8gHCTZD5f9iBXP7w4cz88w/bfDLhAm2fT0jUqpzfIUsywD+p8gUpKTiS0qMnN/s9jXG845Ls6JxwlyfOI+pdJUYPhOotdqY2W4iIZcFUZ35u98SoSA5bK3BQa5yIclSssm9hrVazUQZ1sYapyD4IdqqmYZJbVprNFT9tVJq4ExHI/5gSz9pF9oWak66KBm5IrUGIIhTCjCmU52pbTD49j7mMtq60g8OZlnJzx7nDQxWTzg3QIEbckxWxG/lclu0ebhajAUZ7uIpBNnj2BoEvG0jBJ+JJ8RiC8dg7B9CzDuH2shXbiY2i6cHD9zZWbVe4KNFxx16jSnYJQFpI148cyd8OaKLMbnSTPh5X8J25sw0Ii8DcVuT06gGSpwAvFEvU+H1vsN9rr0WKagGTSjRDa2CMwaAdBqyxaDjIPbR0rU=
  file: tex/paper.pdf
  on:
    repo: CRIStAL-Sigma/reproducible-paper
    tags: true