language: generic
sudo: enabled
os: linux
install:
- ". ./scripts/ensure_latex.sh"
- "./scripts/ensure_book_dependencies.sh"
script:
- cd tex
- pdflatex paper.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  file: tex/paper.pdf
  on:
    repo: CRIStAL-Sigma/reproducible-paper
    tags: true
  api-key:
    secure: TuJZ/s7+lsZ56FoWxlLrJAOLjmMaLSufJYDuauAOWPXAgqJB7MrhZFokeuxiw8C/A+clfenP3DQ1/dfVqkTB/Ir4ny3lclfgkv55XKtLpTDzTxuOErnZGDibv0g8s3VjfGJFr58/+4GGK900mqw6+cHjrzb3auOi3Y3tPuqA0D19sUgzf2TVTYOKK5QeJfS+g+I4aUoCPpAW93N1SOGLLgYJ62Ka1ukC1edKm366rT2j1/JcsqNlubfB1KmXQQXrs4GWGY8VN1W89lFauNGrB0eC0MKGvixci/VfXXcXsDdsVBdSpvrpapRr2OKmr/C6HRaoK+qR6O2Pjg0C8I5GUdvHFunB943mOIIWW0R+7LRmCn5urxsNMpHlHTSvvodcDlcsZAs35P9SgCUYhlWYRib2SJl8rGOqMkxvsDor1IczbQXAeq3QwZ0sUshFNXz7hndfLyScpn8O/hxTS6cLC2YFvGHnx57FML25atajQbnpidutm48N3+Aic4inS09GtB7VaXoghTqfVEOLFRN0jFWNeLKdlsI1AFHtdh6vR3TcPn0b4bx+pxqRtbquL3nmc1JMNZ9hQ50pWiw0onOKVoMJgYSkTYS53DhUV6uWj+3kpryrboVGwFwID2nBhjrmBff1/DYT8oo27FXARmuOxqQtpZBwD+yTemJCaZemi5Q=
